/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   test_template.c                                    :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: alamit <marvin@42.fr>                      +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2018/09/26 19:35:29 by alamit            #+#    #+#             */
/*   Updated: 2018/10/01 16:30:22 by alamit           ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

/* ************************************************************************** */
/*                                                                            */
/*	 This test file was autogenerated by 42framework. You should write your   */
/*	 tests in the main function below. Feel free to check the documentation   */
/*   of the test42f lib on: https://github.com/alamit/42framework.            */
/*                                                                            */
/* ************************************************************************** */

#include <test42f.h>

/* Write your tests in the main function */
int		main(void)
{
	return (0);
}
